MiniballSort: BeamDumpEvt Class Reference
BeamDumpEvt Class Reference
#include <MiniballEvts.hh>
Public Member Functions
BeamDumpEvt ()
~BeamDumpEvt ()
void SetEnergy (float e)
void SetTime (unsigned long long t)
void SetDetector (unsigned char d)
float GetEnergy ()
unsigned long long GetTime ()
unsigned char GetDetector ()
Private Attributes
float energy
energy in keV
unsigned long long time
timestamp of event
unsigned char det
detector ID
Detailed Description
Definition at line 122 of file MiniballEvts.hh.
Constructor & Destructor Documentation
BeamDumpEvt()
BeamDumpEvt::BeamDumpEvt () inline
Definition at line 127 of file MiniballEvts.hh.
~BeamDumpEvt()
BeamDumpEvt::~BeamDumpEvt () inline
Definition at line 128 of file MiniballEvts.hh.
Member Function Documentation
GetDetector()
unsigned char BeamDumpEvt::GetDetector () inline
Definition at line 138 of file MiniballEvts.hh.
GetEnergy()
float BeamDumpEvt::GetEnergy () inline
Definition at line 136 of file MiniballEvts.hh.
GetTime()
unsigned long long BeamDumpEvt::GetTime () inline
Definition at line 137 of file MiniballEvts.hh.
SetDetector()
void BeamDumpEvt::SetDetector (unsigned char d) inline
Definition at line 133 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetEnergy()
void BeamDumpEvt::SetEnergy (float e) inline
Definition at line 131 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetTime()
void BeamDumpEvt::SetTime (unsigned long long t) inline
Definition at line 132 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
Member Data Documentation
det
unsigned char BeamDumpEvt::det private
detector ID
Definition at line 145 of file MiniballEvts.hh.
Referenced by GetDetector(), and SetDetector().
energy
float BeamDumpEvt::energy private
energy in keV
Definition at line 143 of file MiniballEvts.hh.
Referenced by GetEnergy(), and SetEnergy().
time
unsigned long long BeamDumpEvt::time private
timestamp of event
Definition at line 144 of file MiniballEvts.hh.
Referenced by GetTime(), and SetTime().
The documentation for this class was generated from the following file:
include/MiniballEvts.hh