MiniballSort: ParticleEvt Class Reference
ParticleEvt Class Reference
#include <MiniballEvts.hh>
Public Member Functions
ParticleEvt ()
~ParticleEvt ()
void SetEnergyP (float e)
void SetEnergyN (float e)
void SetEnergyPad (float e)
void SetTimeP (unsigned long long t)
void SetTimeN (unsigned long long t)
void SetTimePad (unsigned long long t)
void SetDetector (unsigned char d)
void SetSector (unsigned char s)
void SetStripP (unsigned char s)
void SetStripN (unsigned char s)
float GetEnergy ()
float GetDeltaEnergy ()
float GetRestEnergy ()
unsigned long long GetTime ()
float GetEnergyP ()
float GetEnergyN ()
float GetEnergyPad ()
unsigned long long GetTimeP ()
unsigned long long GetTimeN ()
unsigned long long GetTimePad ()
unsigned char GetDetector ()
unsigned char GetSector ()
unsigned char GetStripP ()
unsigned char GetStripN ()
Private Attributes
float penergy
p-side energy in keV
float nenergy
n-side energy in keV
float padenergy
pad energy in keV
unsigned long long ptime
p-side timestamp of event
unsigned long long ntime
n-side timestamp of event
unsigned long long rtime
pad timestamp of event
unsigned char det
detector ID (=0 for forward CD)
unsigned char sec
sector ID (0-3 for quadrants)
unsigned char pstrip
p-side strip ID
unsigned char nstrip
n-side strip ID
Detailed Description
Definition at line 66 of file MiniballEvts.hh.
Constructor & Destructor Documentation
ParticleEvt()
ParticleEvt::ParticleEvt () inline
Definition at line 71 of file MiniballEvts.hh.
~ParticleEvt()
ParticleEvt::~ParticleEvt () inline
Definition at line 72 of file MiniballEvts.hh.
Member Function Documentation
GetDeltaEnergy()
float ParticleEvt::GetDeltaEnergy () inline
Definition at line 88 of file MiniballEvts.hh.
GetDetector()
unsigned char ParticleEvt::GetDetector () inline
Definition at line 97 of file MiniballEvts.hh.
GetEnergy()
float ParticleEvt::GetEnergy () inline
Definition at line 87 of file MiniballEvts.hh.
GetEnergyN()
float ParticleEvt::GetEnergyN () inline
Definition at line 92 of file MiniballEvts.hh.
GetEnergyP()
float ParticleEvt::GetEnergyP () inline
Definition at line 91 of file MiniballEvts.hh.
Referenced by GetDeltaEnergy(), and GetEnergy().
GetEnergyPad()
float ParticleEvt::GetEnergyPad () inline
Definition at line 93 of file MiniballEvts.hh.
Referenced by GetEnergy(), and GetRestEnergy().
GetRestEnergy()
float ParticleEvt::GetRestEnergy () inline
Definition at line 89 of file MiniballEvts.hh.
GetSector()
unsigned char ParticleEvt::GetSector () inline
Definition at line 98 of file MiniballEvts.hh.
GetStripN()
unsigned char ParticleEvt::GetStripN () inline
Definition at line 100 of file MiniballEvts.hh.
GetStripP()
unsigned char ParticleEvt::GetStripP () inline
Definition at line 99 of file MiniballEvts.hh.
GetTime()
unsigned long long ParticleEvt::GetTime () inline
Definition at line 90 of file MiniballEvts.hh.
GetTimeN()
unsigned long long ParticleEvt::GetTimeN () inline
Definition at line 95 of file MiniballEvts.hh.
GetTimeP()
unsigned long long ParticleEvt::GetTimeP () inline
Definition at line 94 of file MiniballEvts.hh.
Referenced by GetTime().
GetTimePad()
unsigned long long ParticleEvt::GetTimePad () inline
Definition at line 96 of file MiniballEvts.hh.
SetDetector()
void ParticleEvt::SetDetector (unsigned char d) inline
Definition at line 81 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetEnergyN()
void ParticleEvt::SetEnergyN (float e) inline
Definition at line 76 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetEnergyP()
void ParticleEvt::SetEnergyP (float e) inline
Definition at line 75 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetEnergyPad()
void ParticleEvt::SetEnergyPad (float e) inline
Definition at line 77 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetSector()
void ParticleEvt::SetSector (unsigned char s) inline
Definition at line 82 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetStripN()
void ParticleEvt::SetStripN (unsigned char s) inline
Definition at line 84 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetStripP()
void ParticleEvt::SetStripP (unsigned char s) inline
Definition at line 83 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetTimeN()
void ParticleEvt::SetTimeN (unsigned long long t) inline
Definition at line 79 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetTimeP()
void ParticleEvt::SetTimeP (unsigned long long t) inline
Definition at line 78 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetTimePad()
void ParticleEvt::SetTimePad (unsigned long long t) inline
Definition at line 80 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
Member Data Documentation
det
unsigned char ParticleEvt::det private
detector ID (=0 for forward CD)
Definition at line 112 of file MiniballEvts.hh.
Referenced by GetDetector(), and SetDetector().
nenergy
float ParticleEvt::nenergy private
n-side energy in keV
Definition at line 107 of file MiniballEvts.hh.
Referenced by GetEnergyN(), and SetEnergyN().
nstrip
unsigned char ParticleEvt::nstrip private
n-side strip ID
Definition at line 115 of file MiniballEvts.hh.
Referenced by GetStripN(), and SetStripN().
ntime
unsigned long long ParticleEvt::ntime private
n-side timestamp of event
Definition at line 110 of file MiniballEvts.hh.
Referenced by GetTimeN(), and SetTimeN().
padenergy
float ParticleEvt::padenergy private
pad energy in keV
Definition at line 108 of file MiniballEvts.hh.
Referenced by GetEnergyPad(), and SetEnergyPad().
penergy
float ParticleEvt::penergy private
p-side energy in keV
Definition at line 106 of file MiniballEvts.hh.
Referenced by GetEnergyP(), and SetEnergyP().
pstrip
unsigned char ParticleEvt::pstrip private
p-side strip ID
Definition at line 114 of file MiniballEvts.hh.
Referenced by GetStripP(), and SetStripP().
ptime
unsigned long long ParticleEvt::ptime private
p-side timestamp of event
Definition at line 109 of file MiniballEvts.hh.
Referenced by GetTimeP(), and SetTimeP().
rtime
unsigned long long ParticleEvt::rtime private
pad timestamp of event
Definition at line 111 of file MiniballEvts.hh.
Referenced by GetTimePad(), and SetTimePad().
sec
unsigned char ParticleEvt::sec private
sector ID (0-3 for quadrants)
Definition at line 113 of file MiniballEvts.hh.
Referenced by GetSector(), and SetSector().
The documentation for this class was generated from the following file:
include/MiniballEvts.hh