MiniballSort: MiniballParticle Class Reference
MiniballParticle Class Reference
#include <Reaction.hh>
Public Member Functions
MiniballParticle ()
~MiniballParticle ()
double GetMass_u ()
double GetMass ()
int GetA ()
int GetZ ()
int GetN ()
std::string GetIsotope ()
double GetBindingEnergy ()
double GetEnergyTot ()
double GetBeta ()
double GetBetaCoM ()
double GetGamma ()
double GetGammaCoM ()
double GetEnergy ()
double GetEnergyCoM ()
double GetEx ()
double GetTheta ()
double GetThetaCoM ()
double GetPhi ()
TVector3 GetVector ()
double GetMomentum ()
void SetA (int myA)
void SetZ (int myZ)
void SetBindingEnergy (double myBE)
void SetEnergy (double myElab)
void SetEnergyCoM (double myECoM)
void SetEx (double myEx)
void SetTheta (double mytheta)
void SetThetaCoM (double mytheta)
void SetPhi (double myphi)
Private Attributes
int A
mass number, A of the particle, obviously
int Z
The Z of the particle, obviously.
double bindingE
binding energy per nucleon in keV/c^2
double Elab
energy in the laboratory system
double ECoM
energy in the Center-of-Mass system
double Ex
excitation energy of the nucleus
double Theta
theta in the laboratory system in radians
double ThetaCoM
theta in the centre-of-mass system in radians
double Phi
phi in the laboratory system in radians
Detailed Description
A class to read in the reaction file in ROOT's TConfig format. And also to do the physics stuff for the reaction
Definition at line 72 of file Reaction.hh.
Constructor & Destructor Documentation
MiniballParticle()
MiniballParticle::MiniballParticle () inline
Definition at line 77 of file Reaction.hh.
~MiniballParticle()
MiniballParticle::~MiniballParticle () inline
Definition at line 78 of file Reaction.hh.
Member Function Documentation
GetA()
int MiniballParticle::GetA () inline
Definition at line 91 of file Reaction.hh.
Referenced by GetIsotope(), GetMass(), and MiniballReaction::ReadReaction().
GetBeta()
double MiniballParticle::GetBeta () inline
Definition at line 99 of file Reaction.hh.
Referenced by MiniballReaction::DopplerCorrection(), MiniballReaction::DopplerCorrection(), MiniballReaction::DopplerCorrection(), MiniballReaction::GetBeta(), GetGamma(), and MiniballReaction::ReadReaction().
GetBetaCoM()
double MiniballParticle::GetBetaCoM () inline
Definition at line 102 of file Reaction.hh.
Referenced by GetGammaCoM().
GetBindingEnergy()
double MiniballParticle::GetBindingEnergy () inline
Definition at line 97 of file Reaction.hh.
GetEnergy()
double MiniballParticle::GetEnergy () inline
Definition at line 111 of file Reaction.hh.
Referenced by MiniballReaction::GetEnergyPrime(), GetEnergyTot(), MiniballReaction::GetEpsilon(), MiniballReaction::IdentifyEjectile(), and MiniballReaction::ReadReaction().
GetEnergyCoM()
double MiniballParticle::GetEnergyCoM () inline
Definition at line 112 of file Reaction.hh.
GetEnergyTot()
double MiniballParticle::GetEnergyTot () inline
Definition at line 98 of file Reaction.hh.
Referenced by GetBeta(), GetBetaCoM(), MiniballReaction::GetBetaCoM(), MiniballReaction::GetEnergyTotCM(), MiniballReaction::GetEnergyTotLab(), GetMomentum(), and MiniballReaction::TransferProduct().
GetEx()
double MiniballParticle::GetEx () inline
Definition at line 113 of file Reaction.hh.
Referenced by MiniballReaction::GetEnergyPrime(), and GetMass().
GetGamma()
double MiniballParticle::GetGamma () inline
Definition at line 105 of file Reaction.hh.
Referenced by MiniballReaction::DopplerCorrection(), MiniballReaction::DopplerCorrection(), and MiniballReaction::GetGamma().
GetGammaCoM()
double MiniballParticle::GetGammaCoM () inline
Definition at line 108 of file Reaction.hh.
GetIsotope()
std::string MiniballParticle::GetIsotope () inline
Definition at line 94 of file Reaction.hh.
Referenced by MiniballReaction::ReadReaction().
GetMass()
double MiniballParticle::GetMass () inline
Definition at line 84 of file Reaction.hh.
Referenced by MiniballReaction::CalculateEjectile(), MiniballReaction::CalculateRecoil(), GetBetaCoM(), MiniballReaction::GetBetaCoM(), GetEnergyTot(), MiniballReaction::GetEnergyTotCM(), GetMass_u(), GetMomentum(), MiniballReaction::GetQvalue(), MiniballReaction::GetTau(), MiniballReaction::IdentifyEjectile(), MiniballReaction::IdentifyRecoil(), and MiniballReaction::TransferProduct().
GetMass_u()
double MiniballParticle::GetMass_u () inline
Definition at line 81 of file Reaction.hh.
Referenced by MiniballReaction::ReadReaction().
GetMomentum()
double MiniballParticle::GetMomentum () inline
Returns the Lab frame momentum of the particle.
Definition at line 123 of file Reaction.hh.
Referenced by GetBeta(), GetBetaCoM(), MiniballReaction::GetBetaCoM(), and MiniballReaction::TransferProduct().
GetN()
int MiniballParticle::GetN () inline
Definition at line 93 of file Reaction.hh.
Referenced by GetMass().
GetPhi()
double MiniballParticle::GetPhi () inline
Definition at line 116 of file Reaction.hh.
Referenced by MiniballReaction::CalculateEjectile(), MiniballReaction::CalculateRecoil(), GetVector(), and MiniballReaction::TransferProduct().
GetTheta()
double MiniballParticle::GetTheta () inline
Definition at line 114 of file Reaction.hh.
Referenced by GetVector(), and MiniballReaction::TransferProduct().
GetThetaCoM()
double MiniballParticle::GetThetaCoM () inline
Definition at line 115 of file Reaction.hh.
Referenced by MiniballReaction::CalculateEjectile(), MiniballReaction::CalculateRecoil(), MiniballReaction::IdentifyEjectile(), and MiniballReaction::IdentifyRecoil().
GetVector()
TVector3 MiniballParticle::GetVector () inline
Definition at line 117 of file Reaction.hh.
Referenced by MiniballReaction::CosTheta(), MiniballReaction::CosTheta(), and MiniballReaction::DopplerCorrection().
GetZ()
int MiniballParticle::GetZ () inline
Definition at line 92 of file Reaction.hh.
Referenced by GetIsotope(), GetMass(), and MiniballReaction::ReadReaction().
SetA()
void MiniballParticle::SetA (int myA) inline
Definition at line 131 of file Reaction.hh.
Referenced by MiniballReaction::ReadReaction().
SetBindingEnergy()
void MiniballParticle::SetBindingEnergy (double myBE) inline
Definition at line 133 of file Reaction.hh.
Referenced by MiniballReaction::ReadReaction().
SetEnergy()
void MiniballParticle::SetEnergy (double myElab) inline
Definition at line 134 of file Reaction.hh.
Referenced by MiniballReaction::CalculateEjectile(), MiniballReaction::CalculateRecoil(), MiniballReaction::IdentifyEjectile(), MiniballReaction::IdentifyRecoil(), MiniballReaction::ReadReaction(), and MiniballReaction::TransferProduct().
SetEnergyCoM()
void MiniballParticle::SetEnergyCoM (double myECoM) inline
Definition at line 135 of file Reaction.hh.
Referenced by MiniballReaction::TransferProduct().
SetEx()
void MiniballParticle::SetEx (double myEx) inline
Definition at line 136 of file Reaction.hh.
Referenced by MiniballReaction::ReadReaction().
SetPhi()
void MiniballParticle::SetPhi (double myphi) inline
Definition at line 139 of file Reaction.hh.
Referenced by MiniballReaction::CalculateEjectile(), MiniballReaction::CalculateRecoil(), MiniballReaction::IdentifyEjectile(), MiniballReaction::IdentifyRecoil(), and MiniballReaction::TransferProduct().
SetTheta()
void MiniballParticle::SetTheta (double mytheta) inline
Definition at line 137 of file Reaction.hh.
Referenced by MiniballReaction::CalculateEjectile(), MiniballReaction::CalculateRecoil(), MiniballReaction::IdentifyEjectile(), MiniballReaction::IdentifyRecoil(), and MiniballReaction::TransferProduct().
SetThetaCoM()
void MiniballParticle::SetThetaCoM (double mytheta) inline
Definition at line 138 of file Reaction.hh.
Referenced by MiniballReaction::CalculateEjectile(), MiniballReaction::CalculateRecoil(), MiniballReaction::IdentifyEjectile(), MiniballReaction::IdentifyRecoil(), and MiniballReaction::TransferProduct().
SetZ()
void MiniballParticle::SetZ (int myZ) inline
Definition at line 132 of file Reaction.hh.
Referenced by MiniballReaction::ReadReaction().
Member Data Documentation
A
int MiniballParticle::A private
mass number, A of the particle, obviously
Definition at line 145 of file Reaction.hh.
Referenced by GetA(), GetN(), and SetA().
bindingE
double MiniballParticle::bindingE private
binding energy per nucleon in keV/c^2
Definition at line 147 of file Reaction.hh.
Referenced by GetBindingEnergy(), GetMass(), and SetBindingEnergy().
ECoM
double MiniballParticle::ECoM private
energy in the Center-of-Mass system
Definition at line 149 of file Reaction.hh.
Referenced by GetEnergyCoM(), and SetEnergyCoM().
Elab
double MiniballParticle::Elab private
energy in the laboratory system
Definition at line 148 of file Reaction.hh.
Referenced by GetEnergy(), and SetEnergy().
Ex
double MiniballParticle::Ex private
excitation energy of the nucleus
Definition at line 150 of file Reaction.hh.
Referenced by GetEx(), and SetEx().
Phi
double MiniballParticle::Phi private
phi in the laboratory system in radians
Definition at line 153 of file Reaction.hh.
Referenced by GetPhi(), and SetPhi().
Theta
double MiniballParticle::Theta private
theta in the laboratory system in radians
Definition at line 151 of file Reaction.hh.
Referenced by GetTheta(), and SetTheta().
ThetaCoM
double MiniballParticle::ThetaCoM private
theta in the centre-of-mass system in radians
Definition at line 152 of file Reaction.hh.
Referenced by GetThetaCoM(), and SetThetaCoM().
Z
int MiniballParticle::Z private
The Z of the particle, obviously.
Definition at line 146 of file Reaction.hh.
Referenced by GetN(), GetZ(), and SetZ().
The documentation for this class was generated from the following file:
include/Reaction.hh