MiniballSort: MiniballEvts Class Reference
MiniballEvts Class Reference
#include <MiniballEvts.hh>
Public Member Functions
MiniballEvts ()
~MiniballEvts ()
void AddEvt (std::shared_ptr< GammaRayEvt > event)
void AddEvt (std::shared_ptr< GammaRayAddbackEvt > event)
void AddEvt (std::shared_ptr< ParticleEvt > event)
void AddEvt (std::shared_ptr< BeamDumpEvt > event)
void AddEvt (std::shared_ptr< SpedeEvt > event)
void AddEvt (std::shared_ptr< IonChamberEvt > event)
unsigned int GetGammaRayMultiplicity ()
unsigned int GetGammaRayAddbackMultiplicity ()
unsigned int GetParticleMultiplicity ()
unsigned int GetBeamDumpMultiplicity ()
unsigned int GetSpedeMultiplicity ()
unsigned int GetIonChamberMultiplicity ()
std::shared_ptr< GammaRayEvt > GetGammaRayEvt (unsigned int i)
std::shared_ptr< GammaRayAddbackEvt > GetGammaRayAddbackEvt (unsigned int i)
std::shared_ptr< ParticleEvt > GetParticleEvt (unsigned int i)
std::shared_ptr< BeamDumpEvt > GetBeamDumpEvt (unsigned int i)
std::shared_ptr< SpedeEvt > GetSpedeEvt (unsigned int i)
std::shared_ptr< IonChamberEvt > GetIonChamberEvt (unsigned int i)
void ClearEvt ()
void SetEBIS (unsigned long t)
void SetT1 (unsigned long t)
void SetSC (unsigned long t)
void SetLaserStatus (bool l)
unsigned long GetEBIS ()
unsigned long GetT1 ()
unsigned long GetSC ()
bool GetLaserStatus ()
Private Attributes
unsigned long ebis
absolute EBIS pulse time
unsigned long t1
absolute proton pulse time
unsigned long sc
absolute SuperCycle time
bool laser
RILIS laser on (true) or off (false)
std::vector< GammaRayEvt > gamma_event
std::vector< GammaRayAddbackEvt > gamma_ab_event
std::vector< ParticleEvt > particle_event
std::vector< BeamDumpEvt > bd_event
std::vector< SpedeEvt > spede_event
std::vector< IonChamberEvt > ic_event
Detailed Description
Definition at line 255 of file MiniballEvts.hh.
Constructor & Destructor Documentation
MiniballEvts()
MiniballEvts::MiniballEvts () inline
Definition at line 260 of file MiniballEvts.hh.
~MiniballEvts()
MiniballEvts::~MiniballEvts () inline
Definition at line 261 of file MiniballEvts.hh.
Member Function Documentation
AddEvt() [1/6]
void MiniballEvts::AddEvt (std::shared_ptr< BeamDumpEvt > event)
Definition at line 88 of file MiniballEvts.cc.
AddEvt() [2/6]
void MiniballEvts::AddEvt (std::shared_ptr< GammaRayAddbackEvt > event)
Definition at line 54 of file MiniballEvts.cc.
AddEvt() [3/6]
void MiniballEvts::AddEvt (std::shared_ptr< GammaRayEvt > event)
Definition at line 39 of file MiniballEvts.cc.
AddEvt() [4/6]
void MiniballEvts::AddEvt (std::shared_ptr< IonChamberEvt > event)
Definition at line 112 of file MiniballEvts.cc.
AddEvt() [5/6]
void MiniballEvts::AddEvt (std::shared_ptr< ParticleEvt > event)
Definition at line 69 of file MiniballEvts.cc.
AddEvt() [6/6]
void MiniballEvts::AddEvt (std::shared_ptr< SpedeEvt > event)
Definition at line 100 of file MiniballEvts.cc.
ClearEvt()
void MiniballEvts::ClearEvt ()
GetBeamDumpEvt()
std::shared_ptr< BeamDumpEvt > MiniballEvts::GetBeamDumpEvt (unsigned int i) inline
Definition at line 289 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetBeamDumpMultiplicity()
unsigned int MiniballEvts::GetBeamDumpMultiplicity () inline
Definition at line 273 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetEBIS()
unsigned long MiniballEvts::GetEBIS () inline
Definition at line 310 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists(), MiniballHistogrammer::OffBeam(), MiniballHistogrammer::OffBeam(), MiniballHistogrammer::OffBeam(), MiniballHistogrammer::OnBeam(), MiniballHistogrammer::OnBeam(), MiniballHistogrammer::OnBeam(), and MiniballHistogrammer::T1Cut().
GetGammaRayAddbackEvt()
std::shared_ptr< GammaRayAddbackEvt > MiniballEvts::GetGammaRayAddbackEvt (unsigned int i) inline
Definition at line 281 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetGammaRayAddbackMultiplicity()
unsigned int MiniballEvts::GetGammaRayAddbackMultiplicity () inline
Definition at line 271 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetGammaRayEvt()
std::shared_ptr< GammaRayEvt > MiniballEvts::GetGammaRayEvt (unsigned int i) inline
Definition at line 277 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetGammaRayMultiplicity()
unsigned int MiniballEvts::GetGammaRayMultiplicity () inline
Definition at line 270 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetIonChamberEvt()
std::shared_ptr< IonChamberEvt > MiniballEvts::GetIonChamberEvt (unsigned int i) inline
Definition at line 297 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetIonChamberMultiplicity()
unsigned int MiniballEvts::GetIonChamberMultiplicity () inline
Definition at line 275 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetLaserStatus()
bool MiniballEvts::GetLaserStatus () inline
Definition at line 313 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetParticleEvt()
std::shared_ptr< ParticleEvt > MiniballEvts::GetParticleEvt (unsigned int i) inline
Definition at line 285 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetParticleMultiplicity()
unsigned int MiniballEvts::GetParticleMultiplicity () inline
Definition at line 272 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetSC()
unsigned long MiniballEvts::GetSC () inline
Definition at line 312 of file MiniballEvts.hh.
GetSpedeEvt()
std::shared_ptr< SpedeEvt > MiniballEvts::GetSpedeEvt (unsigned int i) inline
Definition at line 293 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetSpedeMultiplicity()
unsigned int MiniballEvts::GetSpedeMultiplicity () inline
Definition at line 274 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillHists().
GetT1()
unsigned long MiniballEvts::GetT1 () inline
Definition at line 311 of file MiniballEvts.hh.
Referenced by MiniballHistogrammer::FillParticleGammaHists(), MiniballHistogrammer::FillParticleGammaHists(), and MiniballHistogrammer::T1Cut().
SetEBIS()
void MiniballEvts::SetEBIS (unsigned long t) inline
Definition at line 305 of file MiniballEvts.hh.
SetLaserStatus()
void MiniballEvts::SetLaserStatus (bool l) inline
Definition at line 308 of file MiniballEvts.hh.
SetSC()
void MiniballEvts::SetSC (unsigned long t) inline
Definition at line 307 of file MiniballEvts.hh.
SetT1()
void MiniballEvts::SetT1 (unsigned long t) inline
Definition at line 306 of file MiniballEvts.hh.
Member Data Documentation
bd_event
std::vector<BeamDumpEvt> MiniballEvts::bd_event private
Definition at line 327 of file MiniballEvts.hh.
Referenced by AddEvt(), ClassImp(), GetBeamDumpEvt(), and GetBeamDumpMultiplicity().
ebis
unsigned long MiniballEvts::ebis private
absolute EBIS pulse time
Definition at line 319 of file MiniballEvts.hh.
Referenced by ClassImp(), GetEBIS(), and SetEBIS().
gamma_ab_event
std::vector<GammaRayAddbackEvt> MiniballEvts::gamma_ab_event private
Definition at line 325 of file MiniballEvts.hh.
Referenced by AddEvt(), ClassImp(), GetGammaRayAddbackEvt(), and GetGammaRayAddbackMultiplicity().
gamma_event
std::vector<GammaRayEvt> MiniballEvts::gamma_event private
Definition at line 324 of file MiniballEvts.hh.
Referenced by AddEvt(), ClassImp(), GetGammaRayEvt(), and GetGammaRayMultiplicity().
ic_event
std::vector<IonChamberEvt> MiniballEvts::ic_event private
Definition at line 329 of file MiniballEvts.hh.
Referenced by AddEvt(), ClassImp(), GetIonChamberEvt(), and GetIonChamberMultiplicity().
laser
bool MiniballEvts::laser private
RILIS laser on (true) or off (false)
Definition at line 322 of file MiniballEvts.hh.
Referenced by GetLaserStatus(), and SetLaserStatus().
particle_event
std::vector<ParticleEvt> MiniballEvts::particle_event private
Definition at line 326 of file MiniballEvts.hh.
Referenced by AddEvt(), ClassImp(), GetParticleEvt(), and GetParticleMultiplicity().
sc
unsigned long MiniballEvts::sc private
absolute SuperCycle time
Definition at line 321 of file MiniballEvts.hh.
Referenced by ClassImp(), GetSC(), and SetSC().
spede_event
std::vector<SpedeEvt> MiniballEvts::spede_event private
Definition at line 328 of file MiniballEvts.hh.
Referenced by AddEvt(), ClassImp(), GetSpedeEvt(), and GetSpedeMultiplicity().
t1
unsigned long MiniballEvts::t1 private
absolute proton pulse time
Definition at line 320 of file MiniballEvts.hh.
Referenced by ClassImp(), GetT1(), and SetT1().
The documentation for this class was generated from the following files:
include/MiniballEvts.hh
src/MiniballEvts.cc