MiniballSort: FebexMWD Class Reference
FebexMWD Class Reference
#include <Calibration.hh>
Public Member Functions
FebexMWD ()
virtual ~FebexMWD ()
void DoMWD ()
void SetTrace (std::vector< unsigned short > t)
void SetRiseTime (unsigned int t)
void SetDecayTime (float t)
void SetFlatTop (unsigned int t)
void SetBaseline (unsigned int t)
void SetWindow (unsigned int t)
void SetDelayTime (unsigned int t)
void SetHoldOff (unsigned int t)
void SetShapingTime (unsigned int t)
void SetIntegrationTime (unsigned int t)
void SetThreshold (unsigned int t)
void SetFraction (float f)
unsigned int NumberOfTriggers ()
float GetEnergy (unsigned int i)
float GetCfdTime (unsigned int i)
std::vector< float > GetEnergies ()
std::vector< float > GetCfdTimes ()
std::vector< float > GetStage1 ()
std::vector< float > GetStage2 ()
std::vector< float > GetStage3 ()
std::vector< float > GetStage4 ()
std::vector< float > GetCfd ()
bool IsClipped ()
TGraph * GetTraceGraph ()
TGraph * GetStage1Graph ()
TGraph * GetStage2Graph ()
TGraph * GetStage3Graph ()
TGraph * GetStage4Graph ()
TGraph * GetCfdGraph ()
Private Member Functions
TGraph * GetGraph (std::vector< float > &t)
TGraph * GetGraph (std::vector< unsigned short > &t)
ClassDef (FebexMWD, 3)
Private Attributes
std::vector< float > energy_list
std::vector< float > cfd_list
std::vector< unsigned short > trace
std::vector< float > stage1
std::vector< float > stage2
std::vector< float > stage3
std::vector< float > stage4
std::vector< float > differential
std::vector< float > shaper
std::vector< float > cfd
unsigned int rise_time
unsigned int flat_top
unsigned int window
unsigned int baseline_length
unsigned int decay_time
unsigned int cfd_delay
unsigned int cfd_hold
unsigned int cfd_shaping_time
unsigned int cfd_integration_time
int threshold
float fraction
bool clipped
Detailed Description
Definition at line 24 of file Calibration.hh.
Constructor & Destructor Documentation
FebexMWD()
FebexMWD::FebexMWD () inline
Definition at line 29 of file Calibration.hh.
~FebexMWD()
virtual FebexMWD::~FebexMWD () inline virtual
Definition at line 30 of file Calibration.hh.
Member Function Documentation
ClassDef()
FebexMWD::ClassDef (FebexMWD , 3) private
DoMWD()
void FebexMWD::DoMWD ()
Referenced by MiniballCalibration::DoMWD(), MiniballMbsConverter::ProcessFebexData(), and MiniballMidasConverter::ProcessTraceData().
GetCfd()
std::vector< float > FebexMWD::GetCfd () inline
Definition at line 65 of file Calibration.hh.
GetCfdGraph()
TGraph * FebexMWD::GetCfdGraph () inline
Definition at line 86 of file Calibration.hh.
GetCfdTime()
float FebexMWD::GetCfdTime (unsigned int i) inline
Definition at line 55 of file Calibration.hh.
Referenced by MiniballMbsConverter::ProcessFebexData().
GetCfdTimes()
std::vector< float > FebexMWD::GetCfdTimes () inline
Definition at line 60 of file Calibration.hh.
GetEnergies()
std::vector< float > FebexMWD::GetEnergies () inline
Definition at line 59 of file Calibration.hh.
GetEnergy()
float FebexMWD::GetEnergy (unsigned int i) inline
Definition at line 51 of file Calibration.hh.
Referenced by MiniballMbsConverter::ProcessFebexData(), and MiniballMidasConverter::ProcessTraceData().
GetGraph() [1/2]
TGraph * FebexMWD::GetGraph (std::vector< float > & t) inline private
Definition at line 115 of file Calibration.hh.
Referenced by GetCfdGraph(), GetGraph(), GetStage1Graph(), GetStage2Graph(), GetStage3Graph(), GetStage4Graph(), and GetTraceGraph().
GetGraph() [2/2]
TGraph * FebexMWD::GetGraph (std::vector< unsigned short > & t) inline private
Definition at line 123 of file Calibration.hh.
GetStage1()
std::vector< float > FebexMWD::GetStage1 () inline
Definition at line 61 of file Calibration.hh.
GetStage1Graph()
TGraph * FebexMWD::GetStage1Graph () inline
Definition at line 74 of file Calibration.hh.
GetStage2()
std::vector< float > FebexMWD::GetStage2 () inline
Definition at line 62 of file Calibration.hh.
GetStage2Graph()
TGraph * FebexMWD::GetStage2Graph () inline
Definition at line 77 of file Calibration.hh.
GetStage3()
std::vector< float > FebexMWD::GetStage3 () inline
Definition at line 63 of file Calibration.hh.
GetStage3Graph()
TGraph * FebexMWD::GetStage3Graph () inline
Definition at line 80 of file Calibration.hh.
GetStage4()
std::vector< float > FebexMWD::GetStage4 () inline
Definition at line 64 of file Calibration.hh.
GetStage4Graph()
TGraph * FebexMWD::GetStage4Graph () inline
Definition at line 83 of file Calibration.hh.
GetTraceGraph()
TGraph * FebexMWD::GetTraceGraph () inline
Definition at line 71 of file Calibration.hh.
IsClipped()
bool FebexMWD::IsClipped () inline
Definition at line 68 of file Calibration.hh.
Referenced by MiniballMidasConverter::ProcessTraceData().
NumberOfTriggers()
unsigned int FebexMWD::NumberOfTriggers () inline
Definition at line 50 of file Calibration.hh.
Referenced by MiniballMbsConverter::ProcessFebexData(), and MiniballMidasConverter::ProcessTraceData().
SetBaseline()
void FebexMWD::SetBaseline (unsigned int t) inline
Definition at line 40 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
SetDecayTime()
void FebexMWD::SetDecayTime (float t) inline
Definition at line 38 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
SetDelayTime()
void FebexMWD::SetDelayTime (unsigned int t) inline
Definition at line 42 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
SetFlatTop()
void FebexMWD::SetFlatTop (unsigned int t) inline
Definition at line 39 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
SetFraction()
void FebexMWD::SetFraction (float f) inline
Definition at line 47 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
SetHoldOff()
void FebexMWD::SetHoldOff (unsigned int t) inline
Definition at line 43 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
SetIntegrationTime()
void FebexMWD::SetIntegrationTime (unsigned int t) inline
Definition at line 45 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
SetRiseTime()
void FebexMWD::SetRiseTime (unsigned int t) inline
Definition at line 37 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
SetShapingTime()
void FebexMWD::SetShapingTime (unsigned int t) inline
Definition at line 44 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
SetThreshold()
void FebexMWD::SetThreshold (unsigned int t) inline
Definition at line 46 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
SetTrace()
void FebexMWD::SetTrace (std::vector< unsigned short > t) inline
Definition at line 36 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
SetWindow()
void FebexMWD::SetWindow (unsigned int t) inline
Definition at line 41 of file Calibration.hh.
Referenced by MiniballCalibration::DoMWD().
Member Data Documentation
baseline_length
unsigned int FebexMWD::baseline_length private
Definition at line 104 of file Calibration.hh.
Referenced by ClassImp(), and SetBaseline().
cfd
std::vector<float> FebexMWD::cfd private
Definition at line 101 of file Calibration.hh.
Referenced by ClassImp(), GetCfd(), and GetCfdGraph().
cfd_delay
unsigned int FebexMWD::cfd_delay private
Definition at line 107 of file Calibration.hh.
Referenced by ClassImp(), and SetDelayTime().
cfd_hold
unsigned int FebexMWD::cfd_hold private
Definition at line 107 of file Calibration.hh.
Referenced by ClassImp(), and SetHoldOff().
cfd_integration_time
unsigned int FebexMWD::cfd_integration_time private
Definition at line 107 of file Calibration.hh.
Referenced by ClassImp(), and SetIntegrationTime().
cfd_list
std::vector<float> FebexMWD::cfd_list private
Definition at line 94 of file Calibration.hh.
Referenced by ClassImp(), GetCfdTime(), and GetCfdTimes().
cfd_shaping_time
unsigned int FebexMWD::cfd_shaping_time private
Definition at line 107 of file Calibration.hh.
Referenced by ClassImp(), and SetShapingTime().
clipped
bool FebexMWD::clipped private
Definition at line 112 of file Calibration.hh.
Referenced by ClassImp(), and IsClipped().
decay_time
unsigned int FebexMWD::decay_time private
Definition at line 104 of file Calibration.hh.
Referenced by ClassImp(), and SetDecayTime().
differential
std::vector<float> FebexMWD::differential private
Definition at line 101 of file Calibration.hh.
Referenced by ClassImp().
energy_list
std::vector<float> FebexMWD::energy_list private
Definition at line 93 of file Calibration.hh.
Referenced by ClassImp(), GetEnergies(), GetEnergy(), and NumberOfTriggers().
flat_top
unsigned int FebexMWD::flat_top private
Definition at line 104 of file Calibration.hh.
Referenced by ClassImp(), and SetFlatTop().
fraction
float FebexMWD::fraction private
Definition at line 109 of file Calibration.hh.
Referenced by ClassImp(), and SetFraction().
rise_time
unsigned int FebexMWD::rise_time private
Definition at line 104 of file Calibration.hh.
Referenced by ClassImp(), and SetRiseTime().
shaper
std::vector<float> FebexMWD::shaper private
Definition at line 101 of file Calibration.hh.
Referenced by ClassImp().
stage1
std::vector<float> FebexMWD::stage1 private
Definition at line 100 of file Calibration.hh.
Referenced by ClassImp(), GetStage1(), and GetStage1Graph().
stage2
std::vector<float> FebexMWD::stage2 private
Definition at line 100 of file Calibration.hh.
Referenced by ClassImp(), GetStage2(), and GetStage2Graph().
stage3
std::vector<float> FebexMWD::stage3 private
Definition at line 100 of file Calibration.hh.
Referenced by ClassImp(), GetStage3(), and GetStage3Graph().
stage4
std::vector<float> FebexMWD::stage4 private
Definition at line 100 of file Calibration.hh.
Referenced by ClassImp(), GetStage4(), and GetStage4Graph().
threshold
int FebexMWD::threshold private
Definition at line 108 of file Calibration.hh.
Referenced by ClassImp(), and SetThreshold().
trace
std::vector<unsigned short> FebexMWD::trace private
Definition at line 97 of file Calibration.hh.
Referenced by ClassImp(), GetTraceGraph(), and SetTrace().
window
unsigned int FebexMWD::window private
Definition at line 104 of file Calibration.hh.
Referenced by ClassImp(), and SetWindow().
The documentation for this class was generated from the following file:
include/Calibration.hh