MiniballSort: GammaRayEvt Class Reference
GammaRayEvt Class Reference
#include <MiniballEvts.hh>
Public Member Functions
GammaRayEvt ()
~GammaRayEvt ()
void SetEnergy (float e)
void SetSegmentSumEnergy (float e)
void SetSegmentMaxEnergy (float e)
void SetSegmentMultiplicity (unsigned int m)
void SetAddbackMultiplicity (unsigned int m)
void SetTime (unsigned long long t)
void SetCluster (unsigned char c)
void SetCrystal (unsigned char c)
void SetSegment (unsigned char s)
float GetEnergy ()
float GetSegmentSumEnergy ()
float GetSegmentMaxEnergy ()
unsigned int GetSegmentMultiplicity ()
unsigned int GetAddbackMultiplicity ()
unsigned long long GetTime ()
unsigned char GetCluster ()
unsigned char GetCrystal ()
unsigned char GetSegment ()
Private Attributes
float energy
energy in keV
float seg_max_energy
energy in keV for the hit segment
float seg_sum_energy
energy in keV for the hit segment
unsigned long long time
timestamp of event
unsigned char seg_mult
segment multiplicity
unsigned char ab_mult
add-back multiplicity
unsigned char clu
cluster ID
unsigned char cry
crystal ID
unsigned char seg
segment ID
Detailed Description
Definition at line 13 of file MiniballEvts.hh.
Constructor & Destructor Documentation
GammaRayEvt()
GammaRayEvt::GammaRayEvt () inline
Definition at line 18 of file MiniballEvts.hh.
~GammaRayEvt()
GammaRayEvt::~GammaRayEvt () inline
Definition at line 19 of file MiniballEvts.hh.
Member Function Documentation
GetAddbackMultiplicity()
unsigned int GammaRayEvt::GetAddbackMultiplicity () inline
Definition at line 37 of file MiniballEvts.hh.
GetCluster()
unsigned char GammaRayEvt::GetCluster () inline
Definition at line 39 of file MiniballEvts.hh.
GetCrystal()
unsigned char GammaRayEvt::GetCrystal () inline
Definition at line 40 of file MiniballEvts.hh.
GetEnergy()
float GammaRayEvt::GetEnergy () inline
Definition at line 33 of file MiniballEvts.hh.
GetSegment()
unsigned char GammaRayEvt::GetSegment () inline
Definition at line 41 of file MiniballEvts.hh.
GetSegmentMaxEnergy()
float GammaRayEvt::GetSegmentMaxEnergy () inline
Definition at line 35 of file MiniballEvts.hh.
GetSegmentMultiplicity()
unsigned int GammaRayEvt::GetSegmentMultiplicity () inline
Definition at line 36 of file MiniballEvts.hh.
GetSegmentSumEnergy()
float GammaRayEvt::GetSegmentSumEnergy () inline
Definition at line 34 of file MiniballEvts.hh.
GetTime()
unsigned long long GammaRayEvt::GetTime () inline
Definition at line 38 of file MiniballEvts.hh.
SetAddbackMultiplicity()
void GammaRayEvt::SetAddbackMultiplicity (unsigned int m) inline
Definition at line 26 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetCluster()
void GammaRayEvt::SetCluster (unsigned char c) inline
Definition at line 28 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetCrystal()
void GammaRayEvt::SetCrystal (unsigned char c) inline
Definition at line 29 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetEnergy()
void GammaRayEvt::SetEnergy (float e) inline
Definition at line 22 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetSegment()
void GammaRayEvt::SetSegment (unsigned char s) inline
Definition at line 30 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetSegmentMaxEnergy()
void GammaRayEvt::SetSegmentMaxEnergy (float e) inline
Definition at line 24 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetSegmentMultiplicity()
void GammaRayEvt::SetSegmentMultiplicity (unsigned int m) inline
Definition at line 25 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetSegmentSumEnergy()
void GammaRayEvt::SetSegmentSumEnergy (float e) inline
Definition at line 23 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetTime()
void GammaRayEvt::SetTime (unsigned long long t) inline
Definition at line 27 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
Member Data Documentation
ab_mult
unsigned char GammaRayEvt::ab_mult private
add-back multiplicity
Definition at line 51 of file MiniballEvts.hh.
Referenced by GetAddbackMultiplicity(), and SetAddbackMultiplicity().
clu
unsigned char GammaRayEvt::clu private
cluster ID
Definition at line 52 of file MiniballEvts.hh.
Referenced by GetCluster(), and SetCluster().
cry
unsigned char GammaRayEvt::cry private
crystal ID
Definition at line 53 of file MiniballEvts.hh.
Referenced by GetCrystal(), and SetCrystal().
energy
float GammaRayEvt::energy private
energy in keV
Definition at line 46 of file MiniballEvts.hh.
Referenced by GetEnergy(), and SetEnergy().
seg
unsigned char GammaRayEvt::seg private
segment ID
Definition at line 54 of file MiniballEvts.hh.
Referenced by GetSegment(), and SetSegment().
seg_max_energy
float GammaRayEvt::seg_max_energy private
energy in keV for the hit segment
Definition at line 47 of file MiniballEvts.hh.
Referenced by GetSegmentMaxEnergy(), and SetSegmentMaxEnergy().
seg_mult
unsigned char GammaRayEvt::seg_mult private
segment multiplicity
Definition at line 50 of file MiniballEvts.hh.
Referenced by GetSegmentMultiplicity(), and SetSegmentMultiplicity().
seg_sum_energy
float GammaRayEvt::seg_sum_energy private
energy in keV for the hit segment
Definition at line 48 of file MiniballEvts.hh.
Referenced by GetSegmentSumEnergy(), and SetSegmentSumEnergy().
time
unsigned long long GammaRayEvt::time private
timestamp of event
Definition at line 49 of file MiniballEvts.hh.
Referenced by GetTime(), and SetTime().
The documentation for this class was generated from the following file:
include/MiniballEvts.hh