MiniballSort: MBSEvent Class Reference
MBSEvent Class Reference
#include <MbsFormat.hh>
Public Member Functions
UInt_t GetTrigger () const
UInt_t GetCount () const
size_t GetNData () const
const UInt_t * GetData () const
ULong_t GetEventID () const
void SetEventID (unsigned long long id)
void Store (UInt_t datum)
void StoreSubEvent (MBSSubEvent _sevt)
unsigned int GetNumberOfSubEvents () const
const MBSSubEvent * GetSubEvent (unsigned int i) const
void Clear ()
void Show (UInt_t verbose=0) const
Private Attributes
std::vector< MBSSubEvent > sevts
std::vector< UInt_t > data
ULong_t eventid
Detailed Description
Definition at line 266 of file MbsFormat.hh.
Member Function Documentation
Clear()
void MBSEvent::Clear () inline
Definition at line 324 of file MbsFormat.hh.
Referenced by MBS::GetNextEventFromStream(), MBS::GetNextLmdEvent(), and MBS::GetNextMedEvent().
GetCount()
UInt_t MBSEvent::GetCount () const inline
Definition at line 283 of file MbsFormat.hh.
Referenced by Show().
GetData()
const UInt_t * MBSEvent::GetData () const inline
Definition at line 294 of file MbsFormat.hh.
Referenced by MiniballMbsConverter::ProcessBlock(), and Show().
GetEventID()
ULong_t MBSEvent::GetEventID () const inline
Definition at line 300 of file MbsFormat.hh.
Referenced by MiniballMbsConverter::ConvertFile(), and MiniballMedConverter::ConvertFile().
GetNData()
size_t MBSEvent::GetNData () const inline
Definition at line 289 of file MbsFormat.hh.
Referenced by MBS::GetNextLmdEvent(), MiniballMbsConverter::ProcessBlock(), and Show().
GetNumberOfSubEvents()
unsigned int MBSEvent::GetNumberOfSubEvents () const inline
Definition at line 317 of file MbsFormat.hh.
Referenced by MiniballMedConverter::ProcessEvent().
GetSubEvent()
const MBSSubEvent * MBSEvent::GetSubEvent (unsigned int i) const inline
Definition at line 318 of file MbsFormat.hh.
Referenced by MiniballMedConverter::ProcessEvent().
GetTrigger()
UInt_t MBSEvent::GetTrigger () const inline
Definition at line 277 of file MbsFormat.hh.
Referenced by Show().
SetEventID()
void MBSEvent::SetEventID (unsigned long long id) inline
Definition at line 303 of file MbsFormat.hh.
Referenced by MBS::ConvertVmeHeader(), and MBS::GetNextLmdEvent().
Show()
void MBSEvent::Show (UInt_t verbose = 0) const inline
Definition at line 330 of file MbsFormat.hh.
Store()
void MBSEvent::Store (UInt_t datum) inline
Definition at line 307 of file MbsFormat.hh.
Referenced by MBS::GetNextLmdEvent().
StoreSubEvent()
void MBSEvent::StoreSubEvent (MBSSubEvent _sevt) inline
Definition at line 312 of file MbsFormat.hh.
Referenced by MBS::GetNextMedEvent().
Member Data Documentation
data
std::vector<UInt_t> MBSEvent::data private
Definition at line 271 of file MbsFormat.hh.
Referenced by Clear(), GetCount(), GetData(), GetNData(), GetTrigger(), and Store().
eventid
ULong_t MBSEvent::eventid private
Definition at line 272 of file MbsFormat.hh.
Referenced by GetEventID(), and SetEventID().
sevts
std::vector<MBSSubEvent> MBSEvent::sevts private
Definition at line 270 of file MbsFormat.hh.
Referenced by Clear(), GetNumberOfSubEvents(), GetSubEvent(), and StoreSubEvent().
The documentation for this class was generated from the following file:
include/MbsFormat.hh