MiniballSort: MiniballDataPackets Class Reference
MiniballDataPackets Class Reference
#include <DataPackets.hh>
Public Member Functions
MiniballDataPackets ()
~MiniballDataPackets ()
MiniballDataPackets (std::shared_ptr< MiniballDataPackets > in)
MiniballDataPackets (std::shared_ptr< DgfData > in)
MiniballDataPackets (std::shared_ptr< AdcData > in)
MiniballDataPackets (std::shared_ptr< FebexData > in)
MiniballDataPackets (std::shared_ptr< InfoData > in)
bool IsDgf () const
bool IsAdc () const
bool IsFebex () const
bool IsInfo () const
void SetData (std::shared_ptr< MiniballDataPackets > in)
void SetData (std::shared_ptr< DgfData > data)
void SetData (std::shared_ptr< AdcData > data)
void SetData (std::shared_ptr< FebexData > data)
void SetData (std::shared_ptr< InfoData > data)
std::shared_ptr< DgfData > GetDgfData () const
std::shared_ptr< AdcData > GetAdcData () const
std::shared_ptr< FebexData > GetFebexData () const
std::shared_ptr< InfoData > GetInfoData () const
unsigned long long int GetEventID () const
long long int GetTime () const
UInt_t GetTimeMSB () const
UInt_t GetTimeLSB () const
unsigned char GetSfp () const
unsigned char GetBoard () const
unsigned char GetModule () const
unsigned char GetChannel () const
bool operator< (const MiniballDataPackets &rhs) const
void ClearData ()
Protected Attributes
std::vector< DgfData > dgf_packets
std::vector< AdcData > adc_packets
std::vector< FebexData > febex_packets
std::vector< InfoData > info_packets
Detailed Description
Definition at line 412 of file DataPackets.hh.
Constructor & Destructor Documentation
MiniballDataPackets() [1/6]
MiniballDataPackets::MiniballDataPackets () inline
Definition at line 416 of file DataPackets.hh.
~MiniballDataPackets()
MiniballDataPackets::~MiniballDataPackets () inline
Definition at line 417 of file DataPackets.hh.
MiniballDataPackets() [2/6]
MiniballDataPackets::MiniballDataPackets (std::shared_ptr< MiniballDataPackets > in) inline
Definition at line 419 of file DataPackets.hh.
MiniballDataPackets() [3/6]
MiniballDataPackets::MiniballDataPackets (std::shared_ptr< DgfData > in) inline
Definition at line 420 of file DataPackets.hh.
MiniballDataPackets() [4/6]
MiniballDataPackets::MiniballDataPackets (std::shared_ptr< AdcData > in) inline
Definition at line 421 of file DataPackets.hh.
MiniballDataPackets() [5/6]
MiniballDataPackets::MiniballDataPackets (std::shared_ptr< FebexData > in) inline
Definition at line 422 of file DataPackets.hh.
MiniballDataPackets() [6/6]
MiniballDataPackets::MiniballDataPackets (std::shared_ptr< InfoData > in) inline
Definition at line 423 of file DataPackets.hh.
Member Function Documentation
ClearData()
void MiniballDataPackets::ClearData ()
Definition at line 121 of file DataPackets.cc.
Referenced by SetData(), SetData(), SetData(), and SetData().
GetAdcData()
std::shared_ptr< AdcData > MiniballDataPackets::GetAdcData () const inline
Definition at line 445 of file DataPackets.hh.
Referenced by MiniballEventBuilder::BuildEvents(), GetBoard(), GetChannel(), GetEventID(), GetModule(), and GetTime().
GetBoard()
unsigned char MiniballDataPackets::GetBoard () const
Definition at line 173 of file DataPackets.cc.
GetChannel()
unsigned char MiniballDataPackets::GetChannel () const
Definition at line 195 of file DataPackets.cc.
GetDgfData()
std::shared_ptr< DgfData > MiniballDataPackets::GetDgfData () const inline
Definition at line 442 of file DataPackets.hh.
Referenced by MiniballEventBuilder::BuildEvents(), GetBoard(), GetChannel(), GetEventID(), GetModule(), and GetTime().
GetEventID()
unsigned long long int MiniballDataPackets::GetEventID () const
Definition at line 130 of file DataPackets.cc.
Referenced by MiniballEventBuilder::BuildEvents().
GetFebexData()
std::shared_ptr< FebexData > MiniballDataPackets::GetFebexData () const inline
Definition at line 448 of file DataPackets.hh.
Referenced by MiniballEventBuilder::BuildEvents(), GetBoard(), GetChannel(), GetEventID(), GetModule(), GetSfp(), and GetTime().
GetInfoData()
std::shared_ptr< InfoData > MiniballDataPackets::GetInfoData () const inline
Definition at line 451 of file DataPackets.hh.
Referenced by MiniballEventBuilder::BuildEvents(), GetBoard(), GetEventID(), GetModule(), GetSfp(), and GetTime().
GetModule()
unsigned char MiniballDataPackets::GetModule () const
Definition at line 184 of file DataPackets.cc.
GetSfp()
unsigned char MiniballDataPackets::GetSfp () const
Definition at line 164 of file DataPackets.cc.
GetTime()
long long int MiniballDataPackets::GetTime () const
Definition at line 141 of file DataPackets.cc.
Referenced by MiniballEventBuilder::BuildEvents(), GetTimeLSB(), GetTimeMSB(), and operator<().
GetTimeLSB()
UInt_t MiniballDataPackets::GetTimeLSB () const
Definition at line 158 of file DataPackets.cc.
GetTimeMSB()
UInt_t MiniballDataPackets::GetTimeMSB () const
Definition at line 152 of file DataPackets.cc.
IsAdc()
bool MiniballDataPackets::IsAdc () const inline
Definition at line 426 of file DataPackets.hh.
Referenced by MiniballEventBuilder::BuildEvents(), GetBoard(), GetChannel(), GetEventID(), GetModule(), and GetTime().
IsDgf()
bool MiniballDataPackets::IsDgf () const inline
Definition at line 425 of file DataPackets.hh.
Referenced by MiniballEventBuilder::BuildEvents(), GetBoard(), GetChannel(), GetEventID(), GetModule(), and GetTime().
IsFebex()
bool MiniballDataPackets::IsFebex () const inline
Definition at line 427 of file DataPackets.hh.
Referenced by MiniballEventBuilder::BuildEvents(), GetBoard(), GetChannel(), GetEventID(), GetModule(), GetSfp(), and GetTime().
IsInfo()
bool MiniballDataPackets::IsInfo () const inline
Definition at line 428 of file DataPackets.hh.
Referenced by MiniballEventBuilder::BuildEvents(), GetBoard(), GetChannel(), GetEventID(), GetModule(), GetSfp(), and GetTime().
operator<()
bool MiniballDataPackets::operator< (const MiniballDataPackets & rhs) const inline
Definition at line 466 of file DataPackets.hh.
SetData() [1/5]
void MiniballDataPackets::SetData (std::shared_ptr< AdcData > data)
Definition at line 53 of file DataPackets.cc.
SetData() [2/5]
void MiniballDataPackets::SetData (std::shared_ptr< DgfData > data)
Definition at line 25 of file DataPackets.cc.
SetData() [3/5]
void MiniballDataPackets::SetData (std::shared_ptr< FebexData > data)
Definition at line 75 of file DataPackets.cc.
SetData() [4/5]
void MiniballDataPackets::SetData (std::shared_ptr< InfoData > data)
Definition at line 102 of file DataPackets.cc.
SetData() [5/5]
void MiniballDataPackets::SetData (std::shared_ptr< MiniballDataPackets > in) inline
Definition at line 430 of file DataPackets.hh.
Referenced by MiniballDataPackets(), MiniballDataPackets(), MiniballDataPackets(), MiniballDataPackets(), MiniballDataPackets(), and SetData().
Member Data Documentation
adc_packets
std::vector<AdcData> MiniballDataPackets::adc_packets protected
Definition at line 475 of file DataPackets.hh.
Referenced by ClearData(), GetAdcData(), IsAdc(), and SetData().
dgf_packets
std::vector<DgfData> MiniballDataPackets::dgf_packets protected
Definition at line 474 of file DataPackets.hh.
Referenced by ClearData(), GetDgfData(), IsDgf(), and SetData().
febex_packets
std::vector<FebexData> MiniballDataPackets::febex_packets protected
Definition at line 476 of file DataPackets.hh.
Referenced by ClearData(), GetFebexData(), IsFebex(), and SetData().
info_packets
std::vector<InfoData> MiniballDataPackets::info_packets protected
Definition at line 477 of file DataPackets.hh.
Referenced by ClearData(), GetInfoData(), IsInfo(), and SetData().
The documentation for this class was generated from the following files:
include/DataPackets.hh
src/DataPackets.cc