MiniballSort: MBSSubEvent Class Reference
MBSSubEvent Class Reference
#include <MbsFormat.hh>
Public Member Functions
void AddData (short datum)
short GetData (unsigned int i) const
unsigned int GetNumberOfData () const
void AddData32 (int datum)
int GetData32 (unsigned int i) const
unsigned int GetNumberOfData32 () const
MBSBufferElem GetSubEventElement () const
unsigned int GetSubEventType () const
std::string GetSubEventDescription () const
unsigned int GetSubEventDataSize () const
unsigned long GetSubEventID () const
unsigned int GetDataLength () const
unsigned char GetProcessorType () const
unsigned char GetCrateID () const
unsigned short GetModuleID () const
void SetSubEventElement (MBSBufferElem _stype)
void SetSubEventID (unsigned long id)
void SetDataLength (unsigned int len)
void SetProcessorType (unsigned char ptype)
void SetCrateID (unsigned char id)
void SetModuleID (unsigned short id)
void Show () const
Private Attributes
std::vector< unsigned short > data
unsigned int data_len
length of the sub event
unsigned long seventid
subevent counter
unsigned char proctype
processor type
unsigned char crateid
crate number
unsigned short modid
module ID
MBSBufferElem stype
type class identifier
Detailed Description
Definition at line 196 of file MbsFormat.hh.
Member Function Documentation
AddData()
void MBSSubEvent::AddData (short datum) inline
Definition at line 211 of file MbsFormat.hh.
Referenced by MBS::GetNextMedEvent().
AddData32()
void MBSSubEvent::AddData32 (int datum) inline
Definition at line 221 of file MbsFormat.hh.
Referenced by MBS::GetNextMedEvent().
GetCrateID()
unsigned char MBSSubEvent::GetCrateID () const inline
Definition at line 240 of file MbsFormat.hh.
GetData()
short MBSSubEvent::GetData (unsigned int i) const inline
Definition at line 214 of file MbsFormat.hh.
Referenced by MiniballMedConverter::ProcessDgfData(), MiniballMedConverter::ProcessDgfScaler(), MiniballMedConverter::ProcessMesytecAdcData(), MiniballMedConverter::ProcessPatternUnitData(), MiniballMedConverter::ProcessScalerData(), and Show().
GetData32()
int MBSSubEvent::GetData32 (unsigned int i) const inline
Definition at line 225 of file MbsFormat.hh.
GetDataLength()
unsigned int MBSSubEvent::GetDataLength () const inline
Definition at line 238 of file MbsFormat.hh.
Referenced by MiniballMedConverter::ProcessDgfData().
GetModuleID()
unsigned short MBSSubEvent::GetModuleID () const inline
Definition at line 241 of file MbsFormat.hh.
Referenced by MiniballMedConverter::ProcessDgfData(), MiniballMedConverter::ProcessDgfScaler(), MiniballMedConverter::ProcessEvent(), MiniballMedConverter::ProcessPatternUnitData(), and MiniballMedConverter::ProcessScalerData().
GetNumberOfData()
unsigned int MBSSubEvent::GetNumberOfData () const inline
Definition at line 218 of file MbsFormat.hh.
Referenced by MiniballMedConverter::ProcessDgfData(), MiniballMedConverter::ProcessDgfScaler(), MiniballMedConverter::ProcessScalerData(), and Show().
GetNumberOfData32()
unsigned int MBSSubEvent::GetNumberOfData32 () const inline
Definition at line 230 of file MbsFormat.hh.
GetProcessorType()
unsigned char MBSSubEvent::GetProcessorType () const inline
Definition at line 239 of file MbsFormat.hh.
GetSubEventDataSize()
unsigned int MBSSubEvent::GetSubEventDataSize () const inline
Definition at line 236 of file MbsFormat.hh.
GetSubEventDescription()
std::string MBSSubEvent::GetSubEventDescription () const inline
Definition at line 235 of file MbsFormat.hh.
Referenced by MiniballMedConverter::ProcessEvent().
GetSubEventElement()
MBSBufferElem MBSSubEvent::GetSubEventElement () const inline
Definition at line 233 of file MbsFormat.hh.
GetSubEventID()
unsigned long MBSSubEvent::GetSubEventID () const inline
Definition at line 237 of file MbsFormat.hh.
Referenced by MiniballMedConverter::ProcessPatternUnitData(), and Show().
GetSubEventType()
unsigned int MBSSubEvent::GetSubEventType () const inline
Definition at line 234 of file MbsFormat.hh.
Referenced by MiniballMedConverter::ProcessDgfData(), MiniballMedConverter::ProcessEvent(), MiniballMedConverter::ProcessPatternUnitData(), MiniballMedConverter::ProcessScalerData(), and Show().
SetCrateID()
void MBSSubEvent::SetCrateID (unsigned char id) inline
Definition at line 248 of file MbsFormat.hh.
Referenced by MBS::GetNextMedEvent().
SetDataLength()
void MBSSubEvent::SetDataLength (unsigned int len) inline
Definition at line 246 of file MbsFormat.hh.
Referenced by MBS::GetNextMedEvent().
SetModuleID()
void MBSSubEvent::SetModuleID (unsigned short id) inline
Definition at line 249 of file MbsFormat.hh.
Referenced by MBS::GetNextMedEvent().
SetProcessorType()
void MBSSubEvent::SetProcessorType (unsigned char ptype) inline
Definition at line 247 of file MbsFormat.hh.
Referenced by MBS::GetNextMedEvent().
SetSubEventElement()
void MBSSubEvent::SetSubEventElement (MBSBufferElem _stype) inline
Definition at line 244 of file MbsFormat.hh.
Referenced by MBS::GetNextMedEvent().
SetSubEventID()
void MBSSubEvent::SetSubEventID (unsigned long id) inline
Definition at line 245 of file MbsFormat.hh.
Referenced by MBS::GetNextMedEvent().
Show()
void MBSSubEvent::Show () const inline
Definition at line 252 of file MbsFormat.hh.
Member Data Documentation
crateid
unsigned char MBSSubEvent::crateid private
crate number
Definition at line 204 of file MbsFormat.hh.
Referenced by GetCrateID(), and SetCrateID().
data
std::vector<unsigned short> MBSSubEvent::data private
Definition at line 200 of file MbsFormat.hh.
Referenced by AddData(), AddData32(), GetData(), GetData32(), GetNumberOfData(), and GetNumberOfData32().
data_len
unsigned int MBSSubEvent::data_len private
length of the sub event
Definition at line 201 of file MbsFormat.hh.
Referenced by GetDataLength(), SetDataLength(), and Show().
modid
unsigned short MBSSubEvent::modid private
module ID
Definition at line 205 of file MbsFormat.hh.
Referenced by GetModuleID(), and SetModuleID().
proctype
unsigned char MBSSubEvent::proctype private
processor type
Definition at line 203 of file MbsFormat.hh.
Referenced by GetProcessorType(), and SetProcessorType().
seventid
unsigned long MBSSubEvent::seventid private
subevent counter
Definition at line 202 of file MbsFormat.hh.
Referenced by GetSubEventID(), and SetSubEventID().
stype
MBSBufferElem MBSSubEvent::stype private
type class identifier
Definition at line 206 of file MbsFormat.hh.
Referenced by GetSubEventDataSize(), GetSubEventDescription(), GetSubEventElement(), GetSubEventType(), and SetSubEventElement().
The documentation for this class was generated from the following file:
include/MbsFormat.hh