MiniballSort: GammaRayAddbackEvt Class Reference
GammaRayAddbackEvt Class Reference
#include <MiniballEvts.hh>
Public Member Functions
GammaRayAddbackEvt ()
~GammaRayAddbackEvt ()
void SetEnergy (float e)
void SetSegmentSumEnergy (float e)
void SetSegmentMaxEnergy (float e)
void SetSegmentMultiplicity (unsigned int m)
void SetAddbackMultiplicity (unsigned int m)
void SetTime (unsigned long long t)
void SetCluster (unsigned char c)
void SetCrystal (unsigned char c)
void SetSegment (unsigned char s)
float GetEnergy ()
float GetSegmentSumEnergy ()
float GetSegmentMaxEnergy ()
unsigned int GetSegmentMultiplicity ()
unsigned int GetAddbackMultiplicity ()
unsigned long long GetTime ()
unsigned char GetCluster ()
unsigned char GetCrystal ()
unsigned char GetSegment ()
Private Attributes
float energy
energy in keV
float seg_max_energy
energy in keV for the hit segment
float seg_sum_energy
energy in keV for the hit segment
unsigned long long time
timestamp of event
unsigned char seg_mult
segment multiplicity
unsigned char ab_mult
add-back multiplicity
unsigned char clu
cluster ID
unsigned char cry
crystal ID
unsigned char seg
segment ID
Detailed Description
Definition at line 61 of file MiniballEvts.hh.
Constructor & Destructor Documentation
GammaRayAddbackEvt()
GammaRayAddbackEvt::GammaRayAddbackEvt () inline
Definition at line 66 of file MiniballEvts.hh.
~GammaRayAddbackEvt()
GammaRayAddbackEvt::~GammaRayAddbackEvt () inline
Definition at line 67 of file MiniballEvts.hh.
Member Function Documentation
GetAddbackMultiplicity()
unsigned int GammaRayEvt::GetAddbackMultiplicity () inline inherited
Definition at line 37 of file MiniballEvts.hh.
GetCluster()
unsigned char GammaRayEvt::GetCluster () inline inherited
Definition at line 39 of file MiniballEvts.hh.
GetCrystal()
unsigned char GammaRayEvt::GetCrystal () inline inherited
Definition at line 40 of file MiniballEvts.hh.
GetEnergy()
float GammaRayEvt::GetEnergy () inline inherited
Definition at line 33 of file MiniballEvts.hh.
GetSegment()
unsigned char GammaRayEvt::GetSegment () inline inherited
Definition at line 41 of file MiniballEvts.hh.
GetSegmentMaxEnergy()
float GammaRayEvt::GetSegmentMaxEnergy () inline inherited
Definition at line 35 of file MiniballEvts.hh.
GetSegmentMultiplicity()
unsigned int GammaRayEvt::GetSegmentMultiplicity () inline inherited
Definition at line 36 of file MiniballEvts.hh.
GetSegmentSumEnergy()
float GammaRayEvt::GetSegmentSumEnergy () inline inherited
Definition at line 34 of file MiniballEvts.hh.
GetTime()
unsigned long long GammaRayEvt::GetTime () inline inherited
Definition at line 38 of file MiniballEvts.hh.
SetAddbackMultiplicity()
void GammaRayEvt::SetAddbackMultiplicity (unsigned int m) inline inherited
Definition at line 26 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetCluster()
void GammaRayEvt::SetCluster (unsigned char c) inline inherited
Definition at line 28 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetCrystal()
void GammaRayEvt::SetCrystal (unsigned char c) inline inherited
Definition at line 29 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetEnergy()
void GammaRayEvt::SetEnergy (float e) inline inherited
Definition at line 22 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetSegment()
void GammaRayEvt::SetSegment (unsigned char s) inline inherited
Definition at line 30 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetSegmentMaxEnergy()
void GammaRayEvt::SetSegmentMaxEnergy (float e) inline inherited
Definition at line 24 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetSegmentMultiplicity()
void GammaRayEvt::SetSegmentMultiplicity (unsigned int m) inline inherited
Definition at line 25 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetSegmentSumEnergy()
void GammaRayEvt::SetSegmentSumEnergy (float e) inline inherited
Definition at line 23 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
SetTime()
void GammaRayEvt::SetTime (unsigned long long t) inline inherited
Definition at line 27 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt(), and MiniballEvts::AddEvt().
Member Data Documentation
ab_mult
unsigned char GammaRayEvt::ab_mult private inherited
add-back multiplicity
Definition at line 51 of file MiniballEvts.hh.
Referenced by GammaRayEvt::GetAddbackMultiplicity(), and GammaRayEvt::SetAddbackMultiplicity().
clu
unsigned char GammaRayEvt::clu private inherited
cluster ID
Definition at line 52 of file MiniballEvts.hh.
Referenced by GammaRayEvt::GetCluster(), and GammaRayEvt::SetCluster().
cry
unsigned char GammaRayEvt::cry private inherited
crystal ID
Definition at line 53 of file MiniballEvts.hh.
Referenced by GammaRayEvt::GetCrystal(), and GammaRayEvt::SetCrystal().
energy
float GammaRayEvt::energy private inherited
energy in keV
Definition at line 46 of file MiniballEvts.hh.
Referenced by GammaRayEvt::GetEnergy(), and GammaRayEvt::SetEnergy().
seg
unsigned char GammaRayEvt::seg private inherited
segment ID
Definition at line 54 of file MiniballEvts.hh.
Referenced by GammaRayEvt::GetSegment(), and GammaRayEvt::SetSegment().
seg_max_energy
float GammaRayEvt::seg_max_energy private inherited
energy in keV for the hit segment
Definition at line 47 of file MiniballEvts.hh.
Referenced by GammaRayEvt::GetSegmentMaxEnergy(), and GammaRayEvt::SetSegmentMaxEnergy().
seg_mult
unsigned char GammaRayEvt::seg_mult private inherited
segment multiplicity
Definition at line 50 of file MiniballEvts.hh.
Referenced by GammaRayEvt::GetSegmentMultiplicity(), and GammaRayEvt::SetSegmentMultiplicity().
seg_sum_energy
float GammaRayEvt::seg_sum_energy private inherited
energy in keV for the hit segment
Definition at line 48 of file MiniballEvts.hh.
Referenced by GammaRayEvt::GetSegmentSumEnergy(), and GammaRayEvt::SetSegmentSumEnergy().
time
unsigned long long GammaRayEvt::time private inherited
timestamp of event
Definition at line 49 of file MiniballEvts.hh.
Referenced by GammaRayEvt::GetTime(), and GammaRayEvt::SetTime().
The documentation for this class was generated from the following file:
include/MiniballEvts.hh