MiniballSort: SpedeEvt Class Reference
SpedeEvt Class Reference
#include <MiniballEvts.hh>
Public Member Functions
SpedeEvt ()
~SpedeEvt ()
void SetEnergy (float e)
void SetTime (unsigned long long t)
void SetSegment (unsigned char s)
float GetEnergy ()
unsigned long long GetTime ()
unsigned char GetSegment ()
Private Attributes
float energy
energy in keV
unsigned long long time
timestamp of event
unsigned char seg
segment ID within SPEDE
Detailed Description
Definition at line 153 of file MiniballEvts.hh.
Constructor & Destructor Documentation
SpedeEvt()
SpedeEvt::SpedeEvt () inline
Definition at line 158 of file MiniballEvts.hh.
~SpedeEvt()
SpedeEvt::~SpedeEvt () inline
Definition at line 159 of file MiniballEvts.hh.
Member Function Documentation
GetEnergy()
float SpedeEvt::GetEnergy () inline
Definition at line 167 of file MiniballEvts.hh.
GetSegment()
unsigned char SpedeEvt::GetSegment () inline
Definition at line 169 of file MiniballEvts.hh.
Referenced by MiniballReaction::GetElectronPhi(), and MiniballReaction::GetElectronTheta().
GetTime()
unsigned long long SpedeEvt::GetTime () inline
Definition at line 168 of file MiniballEvts.hh.
SetEnergy()
void SpedeEvt::SetEnergy (float e) inline
Definition at line 162 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetSegment()
void SpedeEvt::SetSegment (unsigned char s) inline
Definition at line 164 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
SetTime()
void SpedeEvt::SetTime (unsigned long long t) inline
Definition at line 163 of file MiniballEvts.hh.
Referenced by MiniballEvts::AddEvt().
Member Data Documentation
energy
float SpedeEvt::energy private
energy in keV
Definition at line 174 of file MiniballEvts.hh.
Referenced by GetEnergy(), and SetEnergy().
seg
unsigned char SpedeEvt::seg private
segment ID within SPEDE
Definition at line 176 of file MiniballEvts.hh.
Referenced by GetSegment(), and SetSegment().
time
unsigned long long SpedeEvt::time private
timestamp of event
Definition at line 175 of file MiniballEvts.hh.
Referenced by GetTime(), and SetTime().
The documentation for this class was generated from the following file:
include/MiniballEvts.hh