MiniballSort: mb_sort.hh File Reference
mb_sort.hh File Reference
#include <TTree.h>
#include <TFile.h>
#include <THttpServer.h>
#include <TThread.h>
#include <TGClient.h>
#include <TApplication.h>
#include <TCanvas.h>
#include <iostream>
#include <cstdio>
#include <string>
#include <vector>
#include <sstream>
#include <memory>
#include <csignal>
Macros
#define CURDIR "./"
#define AMEDIR "./data"
#define SRIMDIR "./srim"
Functions
void plot_physics_hists ()
void reset_conv_hists ()
void reset_evnt_hists ()
void reset_phys_hists ()
void stop_monitor ()
void start_monitor ()
Variables
Bool_t bRunMon = kTRUE
Bool_t bFirstRun = kTRUE
std::string curFileMon
Macro Definition Documentation
AMEDIR
#define AMEDIR "./data"
Definition at line 27 of file mb_sort.hh.
CURDIR
#define CURDIR "./"
Definition at line 24 of file mb_sort.hh.
SRIMDIR
#define SRIMDIR "./srim"
Definition at line 30 of file mb_sort.hh.
Function Documentation
plot_physics_hists()
void plot_physics_hists ()
reset_conv_hists()
void reset_conv_hists ()
Definition at line 147 of file mb_sort.cc.
Referenced by ResetAll(), and ResetConv().
reset_evnt_hists()
void reset_evnt_hists ()
Definition at line 151 of file mb_sort.cc.
Referenced by ResetAll(), and ResetEvnt().
reset_phys_hists()
void reset_phys_hists ()
Definition at line 155 of file mb_sort.cc.
Referenced by ResetAll(), and ResetHist().
start_monitor()
void start_monitor ()
Definition at line 163 of file mb_sort.cc.
Referenced by StartMonitor().
stop_monitor()
void stop_monitor ()
Definition at line 159 of file mb_sort.cc.
Referenced by StopMonitor().
Variable Documentation
bFirstRun
Bool_t bFirstRun = kTRUE
Definition at line 34 of file mb_sort.hh.
Referenced by monitor_run().
bRunMon
Bool_t bRunMon = kTRUE
Definition at line 33 of file mb_sort.hh.
Referenced by monitor_run(), start_monitor(), and stop_monitor().
curFileMon
std::string curFileMon
Definition at line 35 of file mb_sort.hh.
Referenced by monitor_run().